### DISCUSSION TITLE
Automation

### DISCUSSION THREAD

**Discussion by doula78** [house-of-abbey/GarminHomeAssistant#193] [Q&A] [answered]
Hello,

I just received a Garmin, and I want to add this feature with HA :-)

I have this automation :
```
alias: Activer portail
description: Activer portail
mode: single
triggers:
  - entity_id:
      - switch.portail
    to: "on"
    trigger: state
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - data:
      entity_id: "{{ trigger.entity_id }}"
    action: switch.turn_off
```

But I don't find the correct JSON to call it. Can you please help me ?

I try this kin of test, but it does not work :
```
 {
      "entity": "automation.activer_portail",
      "name": "Portail",
      "type": "tap",
      "tap_action": {
        "service": "automation.trigger",
        "data": {
            "name" : "entity_id",
            "type": "template",
            "content": "{{ trigger.entity_id }}"
        }
      }
    }
```

Thank you !
