### DISCUSSION TITLE
Example for controlling Nuki smart lock from the Garmin app

### DISCUSSION THREAD

**Discussion by Zlate87** [house-of-abbey/GarminHomeAssistant#212] [Q&A] [answered]
Hi,

Does anyone have successfully configured the app to control Nuki smart lock setup with MQTT?

**Comment by Zlate87** [comment, marked as answer]
I was able to easily achieve this by creating an automation with a manual trigger that opens the door:

```
alias: Open Door
description: ""
triggers:
  - trigger: event
    event_type: ""
conditions: []
actions:
  - device_id: [THE_DEVICE_ID]
    domain: lock
    entity_id: [THE_ENTITY_ID]
    type: open
mode: single
```

And then adding the following configuration in the `dashboard.json`:

```
 {
    "entity": "automation.[THE_AUTOMATION_NAME]",
    "name": "Open Door",
    "type": "tap",
    "tap_action": {
        "service": "automation.trigger"
    }
}
```

Later I created a lock toggle automation as well:

```
alias: Toggle Door
description: ""
triggers:
  - trigger: event
    event_type: ""
    context: {}
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: lock.door
            state: locked
        sequence:
          - device_id: [THE_DEVICE_ID]
            domain: lock
            entity_id: [THE_ENTITY_ID]
            type: unlock
      - conditions:
          - condition: state
            entity_id: lock.door
            state: unlocked
        sequence:
          - device_id: [THE_DEVICE_ID]
            domain: lock
            entity_id: [THE_ENTITY_ID]
            type: lock
```

And grouped the actions in the `dashboard.json`:

{
            "name": "Door",
            "title": "Door",
            "type": "group",
            "items": [
                {
                    "entity": "automation.[THE_OPEN_DOOR_AUTOMATION_NAME]",
                    "name": "Open Door",
                    "type": "tap",
                    "tap_action": {
                        "service": "automation.trigger"
                    }
                },
                {
                    "entity": "automation.[THE_TOGGLE_DOOR_AUTOMATION_NAME]",
                    "name": "Toggle Door",
                    "type": "tap",
                    "tap_action": {
                        "service": "automation.trigger"
                    }
                }
            ]
        }
