### ISSUE TITLE
Question: why changing volume is not working?

### ISSUE THREAD

**Issue by jose1711** [house-of-abbey/GarminHomeAssistant#133]
My item definition is as follows:
```json
    {
     "name": "Volume -",
     "type": "template",
     "entity": "media_player.ht_a5000",
     "content": "{{ '.🔈.🔉.🔊.🕱'[:int(state_attr('media_player.ht_a5000', 'volume_level') * 40)] }}",
     "tap_action": {
      "service": "media_player.volume_set",
      "data": {
       "volume_level": "{{ state_attr('media_player.ht_a5000', 'volume_level') - 0.05 }}"
      }
     }
    }
```
This is modeled after https://community.home-assistant.io/t/media-player-volume-up-steps/17677/7 and I can confirm that the following YAML works in developer tool - service call:
```yaml
service: media_player.volume_set
target:
  entity_id: media_player.ht_a5000
data:
  volume_level: "{{ state_attr('media_player.ht_a5000', 'volume_level') - 0.05 }}"
```
The problem is that Garmin HA reports an issue that no JSON has returned from an HTTP request. While I could write a wrapper script I would like to understand why this is not working out of the box. Thanks!
