### ISSUE TITLE
Error: HTTP request did not return JSON

### ISSUE THREAD

**Issue by Aaroneisele55** [house-of-abbey/GarminHomeAssistant#205]
**Describe the bug**
I have the following script in my HA instance:
```
alias: Licht Stufenschaltung
sequence:
  - variables:
      state: |
        {{states(licht)}}
      bri: |
        {{state_attr(licht,"brightness")}}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{state==\"off\" or bri < (255/stufen) or bri==255}}"
        sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness: |
                {{(255/stufen)|int}}
            target:
              entity_id: |
                {{licht}}
    default:
      - action: light.turn_on
        metadata: {}
        data:
          brightness: |
            {{((bri/(255/stufen))|round(0,"floor")+1)*(255/stufen)}}
        target:
          entity_id: |
            {{licht}}
fields:
  licht:
    selector:
      entity: {}
    name: Licht
    required: true
  stufen:
    selector:
      number:
        min: 1
        max: 5
        step: 1
    name: Stufen
    default: 3
    required: true
description: ""

```
The script switches a light in a set number of brightness steps, and it works fine when called from the developer tools or from automations.
That script is accessible in my HA using the action "script.licht_stufenschaltung".
I have the following code in my JSON:
```
{
         
         "name":"Wohnzimmerlichter",
         "title":"Wohnzimmer",
         "type":"group",
         "items":[
            {
               "entity":"light.lichter_wohnzimmer_licht_1_wohnzimmer",
               "name":"Licht vorne",
               "type":"toggle"
            },
            {
               "entity":"light.lichter_wohnzimmer_licht_2_wohnzimmer",
               "name":"Licht hinten",
               "type":"toggle"
            },
            {
               "entity":"light.lichter_wohnzimmer_licht_3_wohnzimmer",
               "name":"Vitrine",
               "type":"toggle"
            },
            {
                    "name": "Licht vorne Helligkeit",
                    "entity": "script.licht_stufenschaltung",
                    "type": "tap",
                    "tap_action": {
                        "service": "script.turn_on",
                        "data": {
                            "stufen": 3,
                            "licht": "light.lichter_wohnzimmer_licht_1_wohnzimmer"
                        }
                    }
                },
                {
                    "name": "Licht hinten Helligkeit",
                    "entity": "script.licht_stufenschaltung",
                    "type": "tap",
                    "tap_action": {
                        "service": "script.turn_on",
                        "data": {
                            "stufen": 3,
                            "licht": "light.lichter_wohnzimmer_licht_2_wohnzimmer"
                        }
                    }
                },
                {
                    "name": "Vitrine Helligkeit",
                    "entity": "script.licht_stufenschaltung",
                    "type": "tap",
                    "tap_action": {
                        "service": "script.turn_on",
                        "data": {
                            "stufen": 3,
                            "licht": "light.lichter_wohnzimmer_licht_3_wohnzimmer"
                        }
                    }
                }
         ]
      }
```
This code should give me control over three lights, which it does successfully, and the `tap_action`s should call the script mentioned before with one of the lights.
However, when clicking the buttons in the app, the app only gives me an error:

![20241231_060414](https://github.com/user-attachments/assets/4d11d176-6076-4d54-b42e-e4de77345206)

The script is also not executed....

**IMPORTANT!**
I have:

- [X] Used HTTPS to access HomeAssistant (with a public certificate)
- [x] Checked that my JSON Syntax is correct ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file) or otherwise)
- [x] Checked that my JSON follows the schema ([options 2, 3, or 4](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [x] Used the online editor to check my JSON against HomeAssistant ([option 1](https://github.com/house-of-abbey/GarminHomeAssistant#editing-the-json-file))
- [X] Checked the [Docs](https://github.com/house-of-abbey/GarminHomeAssistant)
- [X] Checked the [Troubleshooting Guide](https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md)

**To Reproduce**

1. create a script with an input field for an entity and an input field for a number
2. create an element with a `tap_action` that calls this script
3. get the error "HTTP request did not return JSON"

**Expected behavior**
The script should be executed successfully and the app should not give an error

**Screenshots**

**Garmin Device (please complete the following information):**

- Model: Venu 2

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] Samsung S20FE
- OS: [e.g. iOS8.1] Android 13

**Additional context**
