### ISSUE TITLE
I would like to ask about the three problems that have occurred.

### ISSUE THREAD

**Issue by jjy9331** [house-of-abbey/GarminHomeAssistant#40]
```
{
  "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json",
  "title": "gm_ha",
  "items": [
    {
      "entity": "scene.A/C_off",
      "name": "A/C_off",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.A/C_on",
      "name": "A/C_on",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.Air_clean_off",
      "name": "Air_clean_off",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.Air_clean_on",
      "name": "Air_clean_on",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.ct_light_off",
      "name": "ct_light_off",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.ct_light_on",
      "name": "ct_light_on",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.curtain_off",
      "name": "curtain_off",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.curtain_on",
      "name": "curtain_on",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.Light_lang",
      "name": "Light_lang",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.Light_math_science",
      "name": "Light_math_science",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.Light_Night_mood",
      "name": "Light_Night_mood",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.Light_off",
      "name": "Light_off",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.veranda_off",
      "name": "veranda_off",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
    {
      "entity": "scene.veranda_on",
      "name": "veranda_on",
      "type": "tap",
      "tap_action": {
        "service": "scene.turn_on"
      }
    },
  ]
}
```

**Comment by jjy9331** [comment]
Currently, I'm using Garmin Enduro 2
The iPhone is a sledge.
HA uses Raspberry Pie 3b+ as a server
Port forwarding WAN to duckdns
It is composed of https and is in use.


I would like to ask about the three problems that have occurred.


**Question 1**

These three things work well (scene.Air_clean_off, scene.Air_clean_on, and scene.Light_off)

However, the rest will be printed as "executed" but will not work.

What is the reason?
(scene.Light_math_science, scene.Light_Night_mood, etc)


In the readme, the scene was said to be tapable, but no.

I'm comparing and analyzing scenes.yaml and json
I can't think of a suitable solution.



**Question 2**

If the entity and name are spaces or commas(,), an error occurs.


**Question 3**


In the first half-second, api, the menu is displayed as "unconfigured"
In the next 0.5 seconds, api, the menu is output as "available".
And when you click on it, it doesn't run and it goes back to the menu.
And if you click again, the menu is configured and works well.
Is the environment still unstable? Or am I json or
Is url in api a problem? Is json for menu configuration a problem?

**Comment by jjy9331** [comment]
```
- id: '1700051284451'
  name: Light_math_science
  entities:
    light.caegsang_seumateu_jeongu:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6535
      color_temp: 153
      hs_color:
      - 54.768
      - 1.6
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      friendly_name: '책상 스마트 전구 '
      supported_features: 0
      state: 'on'
    light.yeelink_strip6_0fa8_light:
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode: hs
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      model: yeelink.light.strip6
      lan_ip: 172.30.1.72
      mac_address: 58:B6:23:3B:0F:A8
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip6:1
      light.on: true
      light.brightness: 100
      light.color: 16777215
      state_updater: lan
      friendly_name: Yeelight LED Lightstrip 1S Light
      supported_features: 32
      state: 'on'
    light.yeelink_ceil26_abb0_light:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 370
      effect_list:
      - Day
      - Night
      supported_color_modes:
      - brightness
      - color_temp
      - onoff
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6493
      color_temp: 154
      hs_color:
      - 48.348
      - 2.014
      rgb_color:
      - 255
      - 254
      - 249
      xy_color:
      - 0.327
      - 0.334
      effect: Day
      model: yeelink.light.ceil26
      lan_ip: 172.30.1.1
      mac_address: 64:90:C1:A3:AB:B0
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceil26:1
      light.on: true
      light.mode: 0
      light.brightness: 100
      light.color_temperature: 6494
      light.flow: 0
      state_updater: lan
      friendly_name: 천정등 Light
      supported_features: 36
      state: 'on'
    light.seumateu_raiteu_seuteurib:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - bubblingcauldron
      - aurora
      - candycane
      - christmas
      - flicker
      - christmaslight
      - hanukkah
      - hauntedmansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6535
      color_temp: 153
      hs_color:
      - 54.768
      - 1.6
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      effect:
      friendly_name: 스마트 라이트 스트립
      supported_features: 4
      state: 'on'
    light.ct_light:
      effect_list:
      - Night
      - Read
      - Working
      - Leisure
      - Soft
      - Colorful
      - Dazzling
      - Music
      supported_color_modes:
      - hs
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      raw_state: false
      friendly_name: ct_light
      supported_features: 21
      state: 'off'
  icon: mdi:lightbulb
  metadata: {}
- id: '1700051332339'
  name: Light_off
  entities:
    light.caegsang_seumateu_jeongu:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      friendly_name: '책상 스마트 전구 '
      supported_features: 0
      state: 'off'
    light.seumateu_raiteu_seuteurib:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - bubblingcauldron
      - aurora
      - candycane
      - christmas
      - flicker
      - christmaslight
      - hanukkah
      - hauntedmansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      friendly_name: 스마트 라이트 스트립
      supported_features: 4
      state: 'off'
    light.yeelink_strip6_0fa8_light:
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      model: yeelink.light.strip6
      lan_ip: 192.168.0.104
      mac_address: 58:B6:23:3B:0F:A8
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip6:1
      light.on: false
      light.brightness: 100
      light.color: 16777215
      state_updater: lan
      friendly_name: Yeelight LED Lightstrip 1S Light
      supported_features: 32
      state: 'off'
    light.curtain_strip_light:
      effect_list:
      - Night
      - Read
      - Working
      - Leisure
      - Soft
      - Colorful
      - Dazzling
      - Music
      - Music
      supported_color_modes:
      - hs
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      raw_state: false
      friendly_name: curtain strip light
      supported_features: 21
      state: 'off'
    light.yeelink_ceil26_abb0_light:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 370
      effect_list:
      - Day
      - Night
      supported_color_modes:
      - brightness
      - color_temp
      - onoff
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      model: yeelink.light.ceil26
      lan_ip: 192.168.0.105
      mac_address: 64:90:C1:A3:AB:B0
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceil26:1
      light.on: false
      light.mode: 0
      light.brightness: 100
      light.color_temperature: 6494
      light.flow: 0
      state_updater: lan
      friendly_name: 천정등 Light
      supported_features: 36
      state: 'off'
  icon: mdi:lightbulb-off
  metadata: {}
- id: '1700051627723'
  name: Light_Night_mood
  entities:
    light.caegsang_seumateu_jeongu:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: hs
      brightness: 43
      color_temp_kelvin:
      color_temp:
      hs_color:
      - 5
      - 73
      rgb_color:
      - 255
      - 84
      - 68
      xy_color:
      - 0.627
      - 0.315
      friendly_name: '책상 스마트 전구 '
      supported_features: 0
      state: 'on'
    light.yeelink_strip6_0fa8_light:
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode: hs
      brightness: 92
      hs_color:
      - 9.02
      - 60
      rgb_color:
      - 255
      - 125
      - 102
      xy_color:
      - 0.556
      - 0.331
      model: yeelink.light.strip6
      lan_ip: 172.30.1.72
      mac_address: 58:B6:23:3B:0F:A8
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip6:1
      light.on: true
      light.brightness: 36
      light.color: 16743782
      state_updater: lan
      friendly_name: Yeelight LED Lightstrip 1S Light
      supported_features: 32
      state: 'on'
    light.yeelink_ceil26_abb0_light:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 370
      effect_list:
      - Day
      - Night
      supported_color_modes:
      - brightness
      - color_temp
      - onoff
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      model: yeelink.light.ceil26
      lan_ip: 172.30.1.1
      mac_address: 64:90:C1:A3:AB:B0
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceil26:1
      light.on: false
      light.mode: 0
      light.brightness: 100
      light.color_temperature: 5000
      light.flow: 0
      state_updater: lan
      friendly_name: 천정등 Light
      supported_features: 36
      state: 'off'
    light.ct_light:
      effect_list:
      - Night
      - Read
      - Working
      - Leisure
      - Soft
      - Colorful
      - Dazzling
      - Music
      supported_color_modes:
      - hs
      color_mode: hs
      brightness: 64
      hs_color:
      - 329
      - 77.3
      rgb_color:
      - 255
      - 57
      - 159
      xy_color:
      - 0.519
      - 0.234
      effect:
      raw_state: true
      friendly_name: ct_light
      supported_features: 21
      state: 'on'
    light.seumateu_raiteu_seuteurib:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - bubblingcauldron
      - aurora
      - candycane
      - christmas
      - flicker
      - christmaslight
      - hanukkah
      - hauntedmansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: 스마트 라이트 스트립
      supported_features: 4
      color_mode: hs
      brightness: 87
      hs_color:
      - 24
      - 62
      rgb_color:
      - 255
      - 160
      - 96
      xy_color:
      - 0.526
      - 0.374
      state: 'on'
  icon: mdi:power-sleep
  metadata: {}
- id: '1700051942056'
  name: Light_lang
  entities:
    light.caegsang_seumateu_jeongu:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: '책상 스마트 전구 '
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 27.028
      - 18.905
      rgb_color:
      - 255
      - 228
      - 206
      xy_color:
      - 0.371
      - 0.349
      color_temp_kelvin: 5025
      color_temp: 199
      state: 'on'
    light.seumateu_raiteu_seuteurib:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - bubblingcauldron
      - aurora
      - candycane
      - christmas
      - flicker
      - christmaslight
      - hanukkah
      - hauntedmansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: 스마트 라이트 스트립
      supported_features: 4
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 27.001
      - 19.243
      rgb_color:
      - 255
      - 228
      - 205
      xy_color:
      - 0.372
      - 0.35
      color_temp_kelvin: 5000
      color_temp: 200
      state: 'on'
    light.yeelink_strip6_0fa8_light:
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode: hs
      brightness: 255
      hs_color:
      - 24.706
      - 20
      rgb_color:
      - 255
      - 225
      - 204
      xy_color:
      - 0.375
      - 0.348
      model: yeelink.light.strip6
      lan_ip: 172.30.1.72
      mac_address: 58:B6:23:3B:0F:A8
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-strip6:1
      light.on: true
      light.brightness: 100
      light.color: 16769484
      state_updater: lan
      friendly_name: Yeelight LED Lightstrip 1S Light
      supported_features: 32
      state: 'on'
    light.yeelink_ceil26_abb0_light:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6493
      min_mireds: 154
      max_mireds: 370
      effect_list:
      - Day
      - Night
      supported_color_modes:
      - brightness
      - color_temp
      - onoff
      friendly_name: 천정등 Light
      supported_features: 36
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 5000
      color_temp: 200
      hs_color:
      - 27.001
      - 19.243
      rgb_color:
      - 255
      - 228
      - 205
      xy_color:
      - 0.372
      - 0.35
      effect: Day
      model: yeelink.light.ceil26
      lan_ip: 172.30.1.1
      mac_address: 64:90:C1:A3:AB:B0
      entity_class: MiotLightEntity
      home_room: 2853687717 서재
      miot_type: urn:miot-spec-v2:device:light:0000A001:yeelink-ceil26:1
      light.on: true
      light.mode: 0
      light.brightness: 100
      light.color_temperature: 5000
      light.flow: 0
      state_updater: lan
      state: 'on'
    light.ct_light:
      effect_list:
      - Night
      - Read
      - Working
      - Leisure
      - Soft
      - Colorful
      - Dazzling
      - Music
      supported_color_modes:
      - hs
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      raw_state: false
      friendly_name: ct_light
      supported_features: 21
      state: 'off'
  icon: mdi:lightbulb
  metadata: {}
- id: '1700052153032'
  name: Air_clean_on
  entities:
    fan.gonggi_ceongjeonggi:
      preset_modes:
      - Auto
      - Silent
      - Favorite
      - Idle
      preset_mode: Auto
      extra_features: 0
      turbo_mode_supported: false
      button_pressed:
      sleep_time: 75641
      sleep_mode_learn_count: 30
      use_time: 20411400
      sleep_mode: poweroff
      friendly_name: 공기 청정기
      supported_features: 8
      state: 'on'
  icon: mdi:fan
  metadata: {}
- id: '1700052201217'
  name: Air_clean_off
  entities:
    fan.gonggi_ceongjeonggi:
      preset_modes:
      - Auto
      - Silent
      - Favorite
      - Idle
      preset_mode:
      extra_features: 0
      turbo_mode_supported: false
      button_pressed:
      sleep_time: 75641
      sleep_mode_learn_count: 30
      use_time: 20411100
      sleep_mode: poweroff
      friendly_name: 공기 청정기
      supported_features: 8
      state: 'off'
  icon: mdi:fan-off
  metadata: {}
- id: '1700058560282'
  name: A/C_on
  entities:
    climate.eeokeon:
      hvac_modes:
      - 'off'
      - dry
      - cool
      min_temp: 16
      max_temp: 30
      target_temp_step: 1
      fan_modes:
      - LOW
      - MID
      - HIGH
      current_temperature: 22
      temperature: 28
      current_humidity: 38
      fan_mode:
      friendly_name: 에어컨
      supported_features: 9
      state: cool
  icon: mdi:air-conditioner
  metadata: {}
- id: '1700058630186'
  name: A/C_off
  entities:
    climate.eeokeon:
      hvac_modes:
      - 'off'
      - dry
      - cool
      min_temp: 16
      max_temp: 30
      target_temp_step: 1
      fan_modes:
      - LOW
      - MID
      - HIGH
      current_temperature: 22
      temperature: 28
      current_humidity: 56
      fan_mode:
      friendly_name: 에어컨
      supported_features: 9
      state: 'off'
  icon: mdi:air-conditioner
  metadata: {}
- id: '1700899891674'
  name: veranda_off
  entities:
    switch.0x54ef44100054b30f_top:
      friendly_name: aq_sw2 Top
      state: 'on'
    switch.0x54ef44100054b30f_bottom:
      friendly_name: aq_sw2 Bottom
      state: 'off'
    select.0x54ef44100054b30f_mode_switch:
      options:
      - anti_flicker_mode
      - quick_mode
      friendly_name: aq_sw2 Mode switch
      state: unknown
  icon: mdi:ceiling-light-outline
  metadata: {}
- id: '1700899918359'
  name: veranda_on
  entities:
    switch.0x54ef44100054b30f_top:
      friendly_name: aq_sw2 Top
      state: 'on'
    switch.0x54ef44100054b30f_bottom:
      friendly_name: aq_sw2 Bottom
      state: 'off'
    select.0x54ef44100054b30f_mode_switch:
      options:
      - anti_flicker_mode
      - quick_mode
      friendly_name: aq_sw2 Mode switch
      state: unknown
  icon: mdi:ceiling-light
  metadata: {}
- id: '1701664817219'
  name: curtain_on
  entities:
    cover.curtain_motor:
      current_position: 100
      friendly_name: curtain_motor
      supported_features: 15
      state: open
  icon: mdi:curtains
  metadata: {}
- id: '1701664849550'
  name: curtain_off
  entities:
    cover.curtain_motor:
      current_position: 2
      friendly_name: curtain_motor
      supported_features: 15
      state: open
  icon: mdi:curtains-closed
  metadata: {}
- id: '1701852160315'
  name: ct_light_on
  entities:
    light.ct_light:
      effect_list:
      - Night
      - Read
      - Working
      - Leisure
      - Soft
      - Colorful
      - Dazzling
      - Music
      supported_color_modes:
      - hs
      color_mode: hs
      brightness: 69
      hs_color:
      - 320
      - 68.8
      rgb_color:
      - 255
      - 79
      - 196
      xy_color:
      - 0.456
      - 0.216
      effect:
      raw_state: true
      friendly_name: ct_light
      supported_features: 21
      state: 'on'
  icon: mdi:led-strip-variant
  metadata: {}
- id: '1701852189331'
  name: ct_light_off
  entities:
    light.ct_light:
      effect_list:
      - Night
      - Read
      - Working
      - Leisure
      - Soft
      - Colorful
      - Dazzling
      - Music
      supported_color_modes:
      - hs
      color_mode:
      brightness:
      hs_color:
      rgb_color:
      xy_color:
      effect:
      raw_state: false
      friendly_name: ct_light
      supported_features: 21
      state: 'off'
  icon: mdi:led-strip-variant-off
  metadata: {}

```
